version: '3.8'

volumes:
  mysql-volume:

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: rese-laravel
    volumes:
      - ./src/:/var/www/html

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: rese-nginx
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - php
    volumes:
      - ./src/:/var/www/html

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: rese-db
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - mysql-volume:/var/lib/mysql

  nuxt:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
      args:
        - TZ=${TZ}
    container_name: rese-nuxt
    volumes:
      - ./src/nuxt:/var/www/html/nuxt
    ports:
      - ${FRONT_PORT}:3000
    depends_on:
      - nginx

  mail:
    image: mailhog/mailhog
    container_name: rese-mail
    ports:
      - ${MAIL_PORT}:8025