name: Laravel

on: push

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: resepj_test
    env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: resepj_test
        DB_USER_NAME: root
        DB_PASSWORD: test
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "7.4"
      - uses: actions/checkout@v3
      - name: Copy .env
        working-directory: ./src
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        working-directory: ./src
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        working-directory: ./src
        run: php artisan key:generate
      - name: migrate
        working-directory: ./src
        run: |
          php artisan migrate --force
      - name: Directory Permissions
        working-directory: ./src
        run: chmod -R 777 storage bootstrap/cache
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        working-directory: ./src
        run: vendor/bin/phpunit
